language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - coverage run -m unittest discover
  - python manage.py init_db
  - python manage.py create_dummy_data
