version: '3'

services:

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - 9000:9000
    volumes:
      - ./docker/minio/data:/data
      - ./docker/minio/config:/root/.minio
    environment:
      MINIO_ACCESS_KEY: 123456789
      MINIO_SECRET_KEY: 123456789
    command: server /export

  postgresql:
    image: postgres:12
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - ./docker/postgres/data:/var/lib/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    user: root

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - 8080:80
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root

  racoon:
    build: .
    container_name: racoon
    ports:
      - 5000:5000
    environment:
      FLASK_CONFIG: debug
      FLASK_DEBUG: 1
      FLASK_APP: manage.py
    command: flask run --host=0.0.0.0