version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
        environment:
          FLASK_CONFIG: debug
          TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
#      - image: circleci/postgres:9.6.5-alpine-ram
#        environment:
#          POSTGRES_USER: ubuntu
#          POSTGRES_DB: circle_test
#          POSTGRES_PASSWORD: ''
    steps:
      - checkout
      - run: mkdir test-reports
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
#      - run:
#          name: setup Heroku
#          command: bash .circleci/setup-heroku.sh
      - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - 'venv'
      - run:
          command: |
            . venv/bin/activate
            python -m unittest discover
#      - store_artifacts:
#          path: test-reports/
#          destination: tr1
#      - store_test_results:
#          path: test-reports/
      - add_ssh_keys:
          fingerprints:
            - 'ca:2a:a9:a8:99:ad:d0:d7:83:fe:c8:cd:5c:33:38:a5'
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push heroku master
              heroku run python manage.py
              heroku restart
            fi
